server:
  port: 8084
  servlet:
    context-path: '/ead-notification/'

spring:
  application:
    name: ead-notification-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-notification
    username: postgres
    password: masterkey
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://glkaazrv:1co_MLN9HXdtfPXqx36EsiBNMTBsruKj@jackal.rmq.cloudamqp.com/glkaazrv

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
