server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

spring:
  application:
    name: ead-authuser-service
  datasource:
    username: postgres
    password: masterkey
    url: jdbc:postgresql://localhost:5432/ead-authuser
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://glkaazrv:1co_MLN9HXdtfPXqx36EsiBNMTBsruKj@jackal.rmq.cloudamqp.com/glkaazrv

logging:
  level:
    org:
      springframework:
        web: DEBUG
    tech:
      brito:
        ead:
          authuser: INFO
    root: INFO

resilience4j:
  retry:
    instances:
      retryIntance:
        max-attempts: 3
        wait-duration: 5s

