server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

spring:
  application:
    name: ead-course-service
  datasource:
    username: postgres
    password: masterkey
    url: jdbc:postgresql://localhost:5432/ead-course
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  rabbitmq:
    addresses: your url -> Example amqps://gerald:1co_MLN9HXdtfPXqx36EsiBNMTBsruKj@talesof.rmq.cloudamqp.com/rivia

logging:
  level:
    root: INFO
    tech.brito.ead: INFO
    org.springframework.web: DEBUG
