server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/britotech/ead-config-server-repo
          default-label: main
          username: britotech
          password: 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

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost