server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/britotech/ead-config-server-repo
          default-label: main
          username: britotech
          password: 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

ead:
  configServer:
    username: configServer
    password: 'cs123'
  serviceRegistry:
    username: serviceRegistry
    password: 'ead123'

eureka:
  client:
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost